[2025-01-04T12:39:57.463-0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-04T12:39:57.498-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: CovidE2EPipeDag.clean_up_sql_exe manual__2025-01-04T20:19:31.115700+00:00 [queued]>
[2025-01-04T12:39:57.525-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: CovidE2EPipeDag.clean_up_sql_exe manual__2025-01-04T20:19:31.115700+00:00 [queued]>
[2025-01-04T12:39:57.526-0800] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-04T12:39:57.563-0800] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): clean_up_sql_exe> on 2025-01-04 20:19:31.115700+00:00
[2025-01-04T12:39:57.586-0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'CovidE2EPipeDag', 'clean_up_sql_exe', 'manual__2025-01-04T20:19:31.115700+00:00', '--job-id', '1074', '--raw', '--subdir', 'DAGS_FOLDER/CovidE2EPipeDag.py', '--cfg-path', '/var/folders/vm/rn9v1g1j739_mq8j5pfl1yxm0000gn/T/tmp8xyfui6f']
[2025-01-04T12:39:57.594-0800] {standard_task_runner.py:105} INFO - Job 1074: Subtask clean_up_sql_exe
[2025-01-04T12:39:57.571-0800] {standard_task_runner.py:72} INFO - Started process 85754 to run task
[2025-01-04T12:39:57.758-0800] {task_command.py:467} INFO - Running <TaskInstance: CovidE2EPipeDag.clean_up_sql_exe manual__2025-01-04T20:19:31.115700+00:00 [running]> on host Matthews-MacBook-Air.local
[2025-01-04T12:39:58.370-0800] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Matthew Horn' AIRFLOW_CTX_DAG_ID='CovidE2EPipeDag' AIRFLOW_CTX_TASK_ID='clean_up_sql_exe' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T20:19:31.115700+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-04T20:19:31.115700+00:00'
[2025-01-04T12:39:58.375-0800] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-04T12:39:58.452-0800] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/vm/rn9v1g1j739_mq8j5pfl1yxm0000gn/T
[2025-01-04T12:39:58.455-0800] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'snow stage remove @CovidE2EPipeDatabase.raw_dataraw_data_stage/load_staged_data_2025-01-04.sql;                   rm /Users/matthewmac/airflow/helper_scripts/load_staged_data_2025-01-04.sql']
[2025-01-04T12:39:58.467-0800] {subprocess.py:99} INFO - Output:
[2025-01-04T12:40:10.930-0800] {subprocess.py:106} INFO - ╭─ Error ─────────────────────────────────────╮
[2025-01-04T12:40:10.937-0800] {subprocess.py:106} INFO - │ Specified name                              │
[2025-01-04T12:40:10.939-0800] {subprocess.py:106} INFO - │ '@CovidE2EPipeDatabase.raw_dataraw_data_sta │
[2025-01-04T12:40:10.940-0800] {subprocess.py:106} INFO - │ ge/load_staged_data_2025-01-04.sql' is not  │
[2025-01-04T12:40:10.941-0800] {subprocess.py:106} INFO - │ valid name.                                 │
[2025-01-04T12:40:10.942-0800] {subprocess.py:106} INFO - ╰─────────────────────────────────────────────╯
[2025-01-04T12:40:12.855-0800] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-04T12:40:12.911-0800] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-04T12:40:12.914-0800] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=CovidE2EPipeDag, task_id=clean_up_sql_exe, run_id=manual__2025-01-04T20:19:31.115700+00:00, execution_date=20250104T201931, start_date=20250104T203957, end_date=20250104T204012
[2025-01-04T12:40:13.001-0800] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-04T12:40:13.047-0800] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-04T12:40:13.050-0800] {local_task_job_runner.py:245} INFO - ::endgroup::
