[2025-01-10T11:35:17.351-0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-10T11:35:17.366-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: CovidE2EPipeDag.clean_up_sql_exe manual__2025-01-10T19:32:13.017425+00:00 [queued]>
[2025-01-10T11:35:17.385-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: CovidE2EPipeDag.clean_up_sql_exe manual__2025-01-10T19:32:13.017425+00:00 [queued]>
[2025-01-10T11:35:17.387-0800] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-10T11:35:17.412-0800] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): clean_up_sql_exe> on 2025-01-10 19:32:13.017425+00:00
[2025-01-10T11:35:17.418-0800] {standard_task_runner.py:72} INFO - Started process 24508 to run task
[2025-01-10T11:35:17.426-0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'CovidE2EPipeDag', 'clean_up_sql_exe', 'manual__2025-01-10T19:32:13.017425+00:00', '--job-id', '1785', '--raw', '--subdir', 'DAGS_FOLDER/CovidE2EPipeDag.py', '--cfg-path', '/var/folders/vm/rn9v1g1j739_mq8j5pfl1yxm0000gn/T/tmpi4ggsjo0']
[2025-01-10T11:35:17.430-0800] {standard_task_runner.py:105} INFO - Job 1785: Subtask clean_up_sql_exe
[2025-01-10T11:35:17.484-0800] {task_command.py:467} INFO - Running <TaskInstance: CovidE2EPipeDag.clean_up_sql_exe manual__2025-01-10T19:32:13.017425+00:00 [running]> on host Matthews-MacBook-Air.local
[2025-01-10T11:35:17.592-0800] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Matthew Horn' AIRFLOW_CTX_DAG_ID='CovidE2EPipeDag' AIRFLOW_CTX_TASK_ID='clean_up_sql_exe' AIRFLOW_CTX_EXECUTION_DATE='2025-01-10T19:32:13.017425+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-10T19:32:13.017425+00:00'
[2025-01-10T11:35:17.593-0800] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-10T11:35:17.637-0800] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/vm/rn9v1g1j739_mq8j5pfl1yxm0000gn/T
[2025-01-10T11:35:17.638-0800] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'snow stage remove @CovidE2EPipeDatabase.raw_data.raw_data_stage/load_staged_data_2025-01-10.sql || true;                   rm /Users/matthewmac/airflow/helper_scripts/load_staged_data_2025-01-10.sql']
[2025-01-10T11:35:17.646-0800] {subprocess.py:99} INFO - Output:
[2025-01-10T11:35:22.332-0800] {subprocess.py:106} INFO - ╭─ Error ─────────────────────────────────────────────╮
[2025-01-10T11:35:22.334-0800] {subprocess.py:106} INFO - │ Specified name                                      │
[2025-01-10T11:35:22.336-0800] {subprocess.py:106} INFO - │ '@CovidE2EPipeDatabase.raw_data.raw_data_stage/load │
[2025-01-10T11:35:22.337-0800] {subprocess.py:106} INFO - │ _staged_data_2025-01-10.sql' is not valid name.     │
[2025-01-10T11:35:22.338-0800] {subprocess.py:106} INFO - ╰─────────────────────────────────────────────────────╯
[2025-01-10T11:35:22.754-0800] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-10T11:35:22.780-0800] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-10T11:35:22.782-0800] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=CovidE2EPipeDag, task_id=clean_up_sql_exe, run_id=manual__2025-01-10T19:32:13.017425+00:00, execution_date=20250110T193213, start_date=20250110T193517, end_date=20250110T193522
[2025-01-10T11:35:22.825-0800] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-10T11:35:22.848-0800] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-10T11:35:22.850-0800] {local_task_job_runner.py:245} INFO - ::endgroup::
