[2025-01-03T17:44:29.482-0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-03T17:44:29.498-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: CovidE2EPipeDag.fetch_raw scheduled__2025-01-03T09:48:00+00:00 [None]>
[2025-01-03T17:44:29.505-0800] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: CovidE2EPipeDag.fetch_raw scheduled__2025-01-03T09:48:00+00:00 [None]>
[2025-01-03T17:44:29.506-0800] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-01-03T17:44:29.524-0800] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_raw> on 2025-01-03 09:48:00+00:00
[2025-01-03T17:44:29.528-0800] {standard_task_runner.py:72} INFO - Started process 59653 to run task
[2025-01-03T17:44:29.535-0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'CovidE2EPipeDag', 'fetch_raw', 'scheduled__2025-01-03T09:48:00+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/CovidPipeDag.py', '--cfg-path', '/var/folders/vm/rn9v1g1j739_mq8j5pfl1yxm0000gn/T/tmppdisyx2i']
[2025-01-03T17:44:29.538-0800] {standard_task_runner.py:105} INFO - Job 218: Subtask fetch_raw
[2025-01-03T17:44:29.597-0800] {task_command.py:467} INFO - Running <TaskInstance: CovidE2EPipeDag.fetch_raw scheduled__2025-01-03T09:48:00+00:00 [running]> on host Matthews-MacBook-Air.local
[2025-01-03T17:44:29.685-0800] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Matthew Horn' AIRFLOW_CTX_DAG_ID='CovidE2EPipeDag' AIRFLOW_CTX_TASK_ID='fetch_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-03T09:48:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-03T09:48:00+00:00'
[2025-01-03T17:44:29.688-0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-03T17:44:29.688-0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-03T17:44:29.689-0800] {logging_mixin.py:190} INFO - Current task name:fetch_raw state:running start_date:2025-01-04 01:44:29.498878+00:00
[2025-01-03T17:44:29.689-0800] {logging_mixin.py:190} INFO - Dag name:CovidE2EPipeDag and current dag run status:running
[2025-01-03T17:44:29.690-0800] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-03T17:44:59.882-0800] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-01-03T17:44:59.884-0800] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-03T17:44:59.890-0800] {process_utils.py:132} INFO - Sending 15 to group 59653. PIDs of all processes in the group: [59653]
[2025-01-03T17:44:59.891-0800] {process_utils.py:87} INFO - Sending the signal 15 to group 59653
[2025-01-03T17:45:59.906-0800] {process_utils.py:150} WARNING - process psutil.Process(pid=59653, name='python3.9', status='running', started='17:44:29') did not respond to SIGTERM. Trying SIGKILL
[2025-01-03T17:45:59.915-0800] {process_utils.py:87} INFO - Sending the signal 9 to group 59653
[2025-01-03T17:45:59.931-0800] {process_utils.py:80} INFO - Process psutil.Process(pid=59653, name='python3.9', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='17:44:29') (59653) terminated with exit code -9
[2025-01-03T17:45:59.934-0800] {standard_task_runner.py:190} ERROR - ('Job 218 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
